CREATE TABLE "COMPANY" (
  "ID" BIGSERIAL NOT NULL,
  "NAME" VARCHAR(50) DEFAULT NULL,
  "ADDRESS" VARCHAR(255) DEFAULT NULL,
  "ADDRESS_SECONDARY" VARCHAR(255) DEFAULT NULL,
  "IS_INTERNAL" BOOLEAN DEFAULT FALSE,
  "FOUNDING_DATE" DATE DEFAULT NULL,
  "VERSION" BIGINT DEFAULT NULL,
  "CREATED_DATE" TIMESTAMP DEFAULT NULL,
  "CREATED_BY" BIGINT DEFAULT NULL,
  "LAST_MODIFIED_DATE" TIMESTAMP DEFAULT NULL,
  "LAST_MODIFIED_BY" BIGINT DEFAULT NULL,
  "ACTIVE" BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY ("ID"),
  CONSTRAINT company_unique UNIQUE ("NAME")
);
